version: '3.8'

services:
  postgres:
    image: postgres:14
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: anmol
      POSTGRES_PASSWORD: luffyandkat
      POSTGRES_DB: userdb
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./postgres-init.sql:/docker-entrypoint-initdb.d/init.sql

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"

  user-service:
    build:
      context: ./apps/user-service
    ports:
      - "4001:4001"
    environment:
      PORT: 4001
      JWT_SECRET: hello-world
      DATABASE_URL: postgres://anmol:luffyandkat@postgres:5432/userdb
      REDIS_URL: redis://redis:6379
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672
    depends_on:
      - postgres
      - redis
      - rabbitmq

  task-service:
    build:
      context: ./apps/task-service
    ports:
      - "4002:4002"
    environment:
      PORT: 4002
      JWT_SECRET: hello-world
      DATABASE_URL: postgres://anmol:luffyandkat@postgres:5432/taskdb
      REDIS_URL: redis://redis:6379
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672
    depends_on:
      - postgres
      - redis
      - rabbitmq

  notification-service:
    build:
      context: ./apps/notification-service
    ports:
      - "4003:4003"
    environment:
      PORT: 4003
      MONGO_URI: mongodb://mongodb:27017/notifications
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672
    depends_on:
      - mongodb
      - rabbitmq

  api-gateway:
    build:
      context: ./apps/api-gateway
    ports:
      - "4000:4000"
    environment:
      PORT: 4000
      USER_SERVICE_URL: http://user-service:4001
      TASK_SERVICE_URL: http://task-service:4002
      NOTIFICATION_SERVICE_URL: http://notification-service:4003
    depends_on:
      - user-service
      - task-service
      - notification-service

  web:
    build:
      context: ./apps/web
    ports:
      - "5173:5173"
    environment:
      VITE_API_URL: http://localhost:4000
    depends_on:
      - api-gateway

volumes:
  pgdata:
  mongodata: